# This file will be included by the Makefile under the project directory.

FLOAT_O := $(FLOAT:.a=.o)
FLOAT_VFPRINTF_O := $(dir $(FLOAT))FLOAT_vfprintf.o

FLOAT_A_OBJ := $(FLOAT_O) $(FLOAT_VFPRINTF_O)

$(FLOAT): $(FLOAT_A_OBJ)
	ar r $@ $^

$(FLOAT_O): lib-common/FLOAT/FLOAT.c lib-common/FLOAT.h
	@mkdir -p $(dir $@)
	gcc -m32 -O2 -fno-if-conversion -fno-builtin -I$(LIB_COMMON_DIR) -c -o $@ $<

$(FLOAT_VFPRINTF_O): lib-common/FLOAT/FLOAT_vfprintf.c lib-common/FLOAT.h
	@mkdir -p $(dir $@)
	gcc -m32 -O2 -fno-if-conversion -fno-builtin -fno-stack-protector -D_FORTIFY_SOURCE=0 -I$(LIB_COMMON_DIR) -c -o $@ $<
